# Generated by Django 3.0.4 on 2020-03-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddrink',
            name='api_id',
        ),
        migrations.AddField(
            model_name='saveddrink',
            name='image',
            field=models.CharField(default='no image', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddrink',
            name='ingredient',
            field=models.CharField(default='no inredient', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddrink',
            name='instruction',
            field=models.CharField(default='no instructions', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saveddrink',
            name='measurement',
            field=models.CharField(default='no measurement', max_length=300),
            preserve_default=False,
        ),
    ]
