# Generated by Django 3.0.4 on 2020-03-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0004_auto_20200314_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(default=2),
        ),
    ]
