# Generated by Django 3.0.4 on 2020-03-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0007_auto_20200316_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddrink',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drinks', to='virtualbarkeep.Event'),
        ),
    ]
