# Generated by Django 3.0.4 on 2020-03-17 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0008_auto_20200316_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
        migrations.DeleteModel(
            name='EventItems',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
