# Generated by Django 3.0.4 on 2020-03-20 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0009_auto_20200317_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveddrink',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='saveddrink',
            name='measurement',
        ),
        migrations.CreateModel(
            name='SavedDrinkIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='virtualbarkeep.SavedDrink')),
            ],
        ),
    ]
