# Generated by Django 3.0.4 on 2020-03-20 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0010_auto_20200320_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddrinkingredient',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='virtualbarkeep.SavedDrink'),
        ),
    ]
