# Generated by Django 3.0.4 on 2020-03-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0011_auto_20200320_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
            ],
        ),
    ]
