# Generated by Django 3.0.4 on 2020-03-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0012_ingredientlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientList',
            new_name='Ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
