# Generated by Django 3.0.4 on 2020-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0013_auto_20200327_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('drink_id', models.CharField(max_length=20)),
            ],
        ),
    ]
