# Generated by Django 3.0.4 on 2020-04-03 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualbarkeep', '0014_drinklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddrinkingredient',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='virtualbarkeep.SavedDrink'),
        ),
    ]
